/**/controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

#    joint_state_broadcaster:
#      type: joint_state_broadcaster/JointStateBroadcaster

    mirte_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    mirte_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

mirte_arm_controller:
  ros__parameters:
    joints:
      - arm_Rot_joint
      - arm_Shoulder_joint
      - arm_Elbow_joint
      - arm_Wrist_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

mirte_gripper_controller:
  ros__parameters:
    joints:
      - Gripper_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true
