<?xml version="1.0" ?>
<robot name="mirte" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find mirte_gazebo)/urdf/materials.xacro"/>
  <xacro:include filename="$(find mirte_gazebo)/urdf/macros.xacro"/>
  <xacro:include filename="$(find mirte_gazebo)/urdf/ros2_control.xacro"/>
  <xacro:include filename="$(find mirte_gazebo)/urdf/lidar.xacro"/>
  <xacro:include filename="$(find mirte_gazebo)/urdf/camera.xacro"/>
  <xacro:property name="yaml_param_file" value="$(find mirte_gazebo)/config/mirte_dimensions.yaml" />
  <xacro:property name="params" value="${load_yaml(yaml_param_file)}"/>



  <link name="link_chassis">
    <!-- pose and inertial -->
    <pose>0 0 0.015 0 0 0</pose>
    <xacro:inertia_box x="${params['base_len']}" y="${params['base_width']}" z="${params['base_height']}" mass="${params['base_mass']}">
      <origin rpy="0 0 0" xyz="0 0 0.015"/>
    </xacro:inertia_box>

    <!-- body -->
    <collision name="collision_chassis">
      <geometry>
        <mesh filename="file://$(find mirte_gazebo)/meshes/mirte_base.stl" scale="0.001 0.001 0.001"/> -->
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find mirte_gazebo)/meshes/mirte_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <link name="base_link" />

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="link_chassis"/>
  </joint>

<joint name="sonar_front_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin rpy="0 0 0" xyz="0.093 0 0.02" />
    <parent link="link_chassis"/>
    <child link="base_sonar_front"/>
</joint>

<link name="base_sonar_front">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.05 0.037"/>
      </geometry>
    </collision>    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.05 0.037"/>
      </geometry>
    </visual>    
    <inertial>
      <mass value="0.0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
    </inertial>
 </link>


  <xacro:caster name="caster_wheel_back" parent="link_chassis" radius="${params['caster_wheel_radius']}" mass="${params['caster_wheel_mass']}">
    <origin rpy=" 0 0 0" xyz="${params['caster_wheel_center_x_offset']} ${params['caster_wheel_center_y_offset']} ${params['caster_wheel_center_z_offset']}"/>
  </xacro:caster>

  <!-- NOTE: xacro parser adds joint_ -->
  <xacro:wheel name="left_wheel" parent="link_chassis" radius="${params['wheel_radius']}" mass="${params['wheel_mass']}">
    <origin rpy="0 0 0" xyz="${params['wheel_center_x_offset']} ${params['wheel_center_y_offset']} ${params['wheel_center_z_offset']}"/>
    <joint_options>
      <limit effort="10" velocity="8"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint_options>
  </xacro:wheel>

  <!-- NOTE: xacro parser adds joint_ -->
  <xacro:wheel name="right_wheel" parent="link_chassis" radius="${params['wheel_radius']}" mass="${params['wheel_mass']}">
    <origin rpy="0 0 0" xyz="${params['wheel_center_x_offset']} ${-1*params['wheel_center_y_offset']} ${params['wheel_center_z_offset']}"/>
    <joint_options>
      <limit effort="10" velocity="8"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint_options>
  </xacro:wheel>
<!--
 <gazebo>
   <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
     <robotNamespace>/mirte</robotNamespace>
     <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
   </plugin>
 </gazebo>


<gazebo reference="base_sonar_front">        
   <sensor type="ray" name="TeraRanger">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>12</update_rate>
      <ray>
         <scan>
            <horizontal>
               <samples>1</samples>
               <resolution>1</resolution> 
               <min_angle>-0.14835</min_angle>
               <max_angle>0.14835</max_angle>
            </horizontal>
            <vertical>
               <samples>1</samples>
               <resolution>1</resolution> 
               <min_angle>-0.014835</min_angle>
               <max_angle>0.014835</max_angle> 
            </vertical>
         </scan>
         <range>
            <min>0.01</min>
            <max>2</max>
            <resolution>0.01</resolution>
         </range>
      </ray>
      <plugin filename="libgazebo_ros_range.so" name="gazebo_ros_range">
         <gaussianNoise>0.005</gaussianNoise>
         <alwaysOn>true</alwaysOn>
         <updateRate>12</updateRate>
         <topicName>sensor/ir_front</topicName>
         <frameName>base_sonar_front</frameName>
         <radiation>ULTRASOUND</radiation>
         <fov>0.2967</fov>
      </plugin>
   </sensor>  
   </gazebo>
-->

</robot>
