/**:
  ros__parameters:
  #    max_frequency: 50
    distance:
      left:
        name: left
        device: mirte
        pins:
          trigger: GP9
          echo: GP8
      right:
        name: right
        device: mirte
        pins:
          trigger: GP7
          echo: GP6
    device:
      mirte:
        type: pcb
        version: 0.8
        board: pico

    #encoder:
    #  left:
    #    name: left
    #    device: mirte
    #    pins:
    #      pin: GP14
    #  right:
    #    name: right
    #    device: mirte
    #    pins:
    #      pin: GP15
    intensity:
      left:
        name: left
        device: mirte
        pins:
          analog: GP27
          digital: GP17
      right:
        name: right
        device: mirte
        pins:
          analog: GP26
          digital: GP16
    oled:
      left:
        name: left
        device: mirte
        pins:
          sda: GP10
          scl: GP11
      right:
        name: right
        device: mirte
        pins:
          sda: GP4
          scl: GP5
    servo:
      left:
        name: left
        device: mirte
        pins:
          pin: GP14
      right:
        name: right
        device: mirte
        pins:
          pin: GP15
      # These servo's have the same pins as the ObjectDetectors. So as
      # soon as they are implemented, these should be commented out
      gripper:
        name: gripper
        device: mirte
        pins:
          pin: GP12
      arm:
        name: arm
        device: mirte
        pins:
          pin: GP13
    keypad:
      yellow:
        name: yellow
        device: mirte
        pins:
          pin: GP28
    motor:
      left:
        name: left
        device: mirte
        type: pp
        pins:
          p1: GP18
          p2: GP19
      right:
        name: right
        device: mirte
        type: pp
        pins:
          p1: GP20
          p2: GP21
    modules:
      motorservocontroller:
        device: mirte
        type: PCA9685
        id: 0x41 # bridged A0
        connector: I2C1
        frequency: 1500
        motors:
          left_rear:
            pin_A: 6 #0
            pin_B: 7 #1
          left_front:
            pin_A: 2
            pin_B: 3
          right_rear:
            pin_A: 5
            pin_B: 4
          right_front:
            pin_A: 1
            pin_B: 0

    # These motors have the same pins as the line intensity sensors. So
    # when uncommenting these, please comment the intensity sensors.
    #  left2:
    #    name: left2
    #    device: mirte
    #    type: pp
    #    pins:
    #      p1: GP26
    #      p2: GP16
    #  right2:
    #    name: right2
    #    device: mirte
    #    type: pp
    #    pins:
    #      p1: GP27
    #      p2: GP17
