mirte_telemetrix:
  ros__parameters:
    device:
      mirte:
        type: breadboard
        board: pico
        max_frequency: 100
    distance:
      left:
        name: left
        device: mirte
        pins:
          trigger: GP9
          echo: GP8
      right:
        name: right
        device: mirte
        pins:
          trigger: GP7
          echo: GP6
   keypad:
     yellow:
       name: yellow
       device: mirte
       pins:
         pin: GP28
   intensity:
     left:
       name: left
       device: mirte
       pins:
         analog: GP27
         digital: GP17
      right:
        name: right
        device: mirte
        pins:
          analog: GP26
          digital: GP16
   oled:
     left:
       name: left
       device: mirte
       pins:
         scl: 5
         sda: 4
    servo:
      left:
        name: left
        device: mirte
        pins:
          pin: GP14
      right:
        name: right
        device: mirte
        pins:
          pin: GP15
      # These servo's have the same pins as the ObjectDetectors. So as
      # soon as they are implemented, these should be commented out
      gripper:
        name: gripper
        device: mirte
        pins:
          pin: GP12
      arm:
        name: arm
        device: mirte
        pins:
          pin: GP13
    motor:
      left:
        name: left
        device: mirte
        type: pp
        pins:
          p1: 18             # pin needs PWM
          p2: 19             # pin needs PWM
      right:
        name: right
        device: mirte
        type: pp
        pins:
          p1: 20            # pin needs PWM
          p2: 21            # pin needs PWM
