name: ros-ci
on:
  pull_request:
  push:

jobs:
  build_test_ros:
    runs-on: ubuntu-22.04
          # you can specify the version after `-` like `llvm-13.0.0`.
    container:
        image: ubuntu:jammy
    steps:
      - uses: actions/checkout@v4
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: mirte_telemetrix_cpp
          target-ros2-distro: humble
          ref: ${{ steps.extract_branch.outputs.branch }}
          vcs-repo-file-url: "${{ github.workspace }}/.github/workflows/repos.repos"
