name: colcon-lint

on: [push, pull_request]

jobs:
  colcon-lint:
    runs-on: ubuntu-latest
    container: osrf/ros:humble-desktop-jammy #faster than using setup-ros
    steps:
    - uses: actions/checkout@v4
    # - uses: ros-tooling/setup-ros@master
    #   with:
    #         required-ros-distributions: 'humble'
    - run: |
        sudo apt install apt-rdepends -y
        pip install colcon-lint
    - name: colcon lint
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --continue-on-error --cmake-args -Wno-dev --trace-expand --trace-redirect=trace.log
        # for every folder in the workspace starting with mirte_ excluding mirte_teleop, run command
        for d in mirte_*; do
          if [ "$d" != "mirte_teleop" ]; then
            colcon lint --packages-select $d
          fi
        done
