name: test-clang-format

on: [push, pull_request]

jobs:
  colcon-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ros-tooling/setup-ros@master
      with:
            required-ros-distributions: 'humble'
    - run: |
        sudo apt install apt-rdepends -y
        pip install colcon-lint
    - name: colcon lint
      run: colcon lint
