name: test-clang-format

on: [push, pull_request]

jobs:
  cpp_style_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: '.'
        exclude: './mirte_telemetrix_cpp/libs/*'
        extensions: 'c,h,cpp,hpp'
        clangFormatVersion: 14
        style: llvm